/*
 * star world API
 *
 * the api to query the information about *Star War* you can check all the Star Wars data you've ever wanted Planets Spaceships Vehicles People Films and Species From all SEVEN Star Wars films 
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LinkList struct {

	// 记录数 
	Count int32 `json:"count,omitempty"`

	// 下一页（最后一页时该值为null） 
	Next string `json:"next,omitempty"`

	// 上一页（第一页时该值为null） 
	Previous string `json:"previous,omitempty"`
}
