/*
 * star world API
 *
 * the api to query the information about *Star War* you can check all the Star Wars data you've ever wanted Planets Spaceships Vehicles People Films and Species From all SEVEN Star Wars films 
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// the response type of people
type People struct {

	// 记录被创建的时间 
	Created time.Time `json:"created,omitempty"`

	// 记录被编辑的时间 
	Edited time.Time `json:"edited,omitempty"`

	// 当前资源的URL 
	Url string `json:"url,omitempty"`

	Name string `json:"name,omitempty"`

	Height string `json:"height,omitempty"`

	Mass string `json:"mass,omitempty"`

	HairColor string `json:"hair_color,omitempty"`

	SkinColor string `json:"skin_color,omitempty"`

	EyeColor string `json:"eye_color,omitempty"`

	BirthYear string `json:"birth_year,omitempty"`

	Gender string `json:"gender,omitempty"`

	Homeworld string `json:"homeworld,omitempty"`

	Films []string `json:"films,omitempty"`

	Species []string `json:"species,omitempty"`

	Vehicles []string `json:"vehicles,omitempty"`

	Starships []string `json:"starships,omitempty"`
}
