/*
 * star world API
 *
 * the api to query the information about *Star War* you can check all the Star Wars data you've ever wanted Planets Spaceships Vehicles People Films and Species From all SEVEN Star Wars films 
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

// the response type of species
type Species struct {

	// 记录被创建的时间 
	Created time.Time `json:"created,omitempty"`

	// 记录被编辑的时间 
	Edited time.Time `json:"edited,omitempty"`

	// 当前资源的URL 
	Url string `json:"url,omitempty"`

	Name string `json:"name,omitempty"`

	Classification string `json:"classification,omitempty"`

	Designation string `json:"designation,omitempty"`

	AverageHeight string `json:"average_height,omitempty"`

	SkinColors string `json:"skin_colors,omitempty"`

	HairColors string `json:"hair_colors,omitempty"`

	EyeColors string `json:"eye_colors,omitempty"`

	AverageLifespan string `json:"average_lifespan,omitempty"`

	Homeworld string `json:"homeworld,omitempty"`

	Language string `json:"language,omitempty"`

	People []string `json:"people,omitempty"`

	Films []string `json:"films,omitempty"`
}
