/*
 * star world API
 *
 * the api to query the information about *Star War* you can check all the Star Wars data you've ever wanted Planets Spaceships Vehicles People Films and Species From all SEVEN Star Wars films
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package apiType

type UserInfo struct {

	// 返回状态
	Status string `json:"status"`

	// 用户名
	Username string `json:"username"`

	// 邮箱地址
	Email string `json:"email"`
}

type StatusOnly struct {

	// 返回状态
	Status string `json:"status"`
}

type FailInfo struct {

	// 返回状态
	Status string `json:"status"`

	// 返回信息
	Message string `json:"message"`
}
