/*
 * star world API
 *
 * the api to query the information about *Star War* you can check all the Star Wars data you've ever wanted Planets Spaceships Vehicles People Films and Species From all SEVEN Star Wars films
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package apiType

type UserNew struct {

	// 申请注册的用户名
	Username string `json:"username"`

	// 申请注册的用户密码
	Password string `json:"password"`

	// 申请注册的邮箱地址
	Email string `json:"email"`
}
